Scorpion/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # Otras URLS de tu aplicación
    path('crear_cliente/', views.crear_cliente, name='crear_cliente'),
    path('crear_cita/', views.crear_cita, name='crear_cita'),
    path('', views.index, name="index"),
    path('servicios/', views.servicios, name="servicios"),
    path('confirmacion/', views.confirmacion, name="confirmacion"),
    path('citas/', views.citas, name='citas'),
]

Scorpion_Project/urls.py
from django.contrib import admin
from django.urls import path, include




urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Scorpion.urls')),
    
]

Scorpion/models.py
from django.db import models
from django.utils import timezone

class Cliente(models.Model):
    rut = models.CharField(max_length=12)
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    telefono = models.CharField(max_length=20)
    email = models.EmailField()

    def __str__(self):
        return f"{self.nombre} {self.apellido}"

    class Meta:
        verbose_name_plural = "Clientes"

class Servicio(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    duracion = models.PositiveIntegerField(verbose_name="Minutos")

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = "Servicios"

class Cita(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    servicio = models.ManyToManyField(Servicio)
    fecha = models.DateField()
    hora = models.TimeField()

    def __str__(self):
        return f'Cita {self.id} - {self.cliente.nombre} {self.cliente.apellido}'

    class Meta:
        verbose_name_plural = "Citas"

Scorpion/forms.py
from django import forms
from django.shortcuts import render
from Scorpion.models import Cliente, Cita
from datetime import datetime, timedelta, time



class ClienteForm(forms.ModelForm):
    rut = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Ej: 21078145-K', 'maxlength': '12', 'oninput': 'formatRut(this)'}),
        max_length=12,
        min_length=9,
    )

    def clean_rut(self):
        rut = self.cleaned_data['rut']
        rut_limpio = rut.replace(".", "").replace("-", "").upper()
        cliente_existente = Cliente.objects.filter(rut=rut_limpio).exists()
        if cliente_existente:
            self.cliente_existente = True
        return rut_limpio

    class Meta:
        model = Cliente
        fields = ['rut', 'nombre', 'apellido', 'telefono', 'email']



class CitaForm(forms.ModelForm):
    class Meta:
        model = Cita
        fields = ['cliente', 'servicio', 'fecha', 'hora']
        widgets = {
            'fecha': forms.DateInput(attrs={'type': 'date', 'min': datetime.now().strftime('%Y-%m-%d'), 'max': (datetime.now() + timedelta(weeks=4)).strftime('%Y-%m-%d')}),
            'hora': forms.TimeInput(attrs={'type': 'time', 'min': time(8, 0).strftime('%H:%M'), 'max': time(17, 30).strftime('%H:%M')}),
            'servicio': forms.SelectMultiple(attrs={'size': 5, 'class': 'custom-service'}),

        }

    def clean_hora(self):
        hora = self.cleaned_data['hora']

        if hora < time(8, 0) or hora > time(17, 30):
            raise forms.ValidationError("El horario de Scorpion es de 08:00 a 17:30")

        fecha = self.cleaned_data['fecha']

        # Filtrar citas existentes para la misma fecha y hora seleccionada
        citas_existentes = Cita.objects.filter(fecha=fecha, hora=hora)

        if citas_existentes.exists():
            raise forms.ValidationError("La hora seleccionada no está disponible. Por favor, elija otra hora.")

        return hora

Scorpion/views.py
from django.shortcuts import render, redirect
from .forms import ClienteForm
from .models import Cliente

# Create your views here.

from django.shortcuts import render, redirect
from .forms import ClienteForm, CitaForm
from .models import Cliente, Cita

def crear_cliente(request):
    cliente_existente = False

    if request.method == 'POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            rut_limpio = form.cleaned_data['rut']
            cliente_existente = Cliente.objects.filter(rut=rut_limpio).exists()
            if cliente_existente:
                form.add_error('rut', '')
            else:
                form.save()
                return redirect('crear_cita')
    else:
        form = ClienteForm()

    context = {
        'form': form,
        'cliente_existente': cliente_existente
    }
    
    return render(request, 'cliente_form.html', context)


def crear_cita(request):
    if request.method == 'POST':
        form = CitaForm(request.POST)
        if form.is_valid():
            cita = form.save()

            # Obtener los datos de la cita recién creada
            cliente = cita.cliente
            hora = cita.hora
            fecha = cita.fecha
            servicios = cita.servicio.all()

            # Pasar los datos a la plantilla de confirmación
            context = {
                'cliente': cliente,
                'hora': hora,
                'fecha': fecha,
                'servicios': servicios,
            }

            return render(request, 'confirmacion.html', context)
    else:
        form = CitaForm()
    
    return render(request, 'cita_form.html', {'form': form})


def index(request):
    return render(request,'index.html')

def servicios(request):
    return render(request, 'servicios.html')

def confirmacion(request):
    return render(request,'confirmacion.html')

def citas(request):
    citas = Cita.objects.all()
    return render(request, 'citas.html', {'citas': citas})

Scorpion/templates/cita_form.html
{% load static %} {% load custom_filters %}

<!DOCTYPE html>
<html>
  <head>
    <title>Crear Cita</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css"
    />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
    <script>
      $(document).ready(function () {
        $("#id_servicio").select2();
      });
    </script>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/test.css' %}" />
    <link rel="icon" type="image/png" href="{% static 'img/lobster.png' %}" />
  </head>

  <body class="btn-dark">
    <br />
    <br />
    <br />
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-11 col-md-8 col-lg-6 col-xl-5">
          <form method="post">
            {% csrf_token %}
            <div class="card custom-card">
              <div class="row mt-0">
                <div class="col-md-12">
                  <h4 class="">Crear Cita</h4>
                </div>
              </div>
              <div class="form-group row mb-3">
                <div class="col-md-12 mb-0">
                  <br />
                  <p class="mb-1">Cliente:</p>
                  {{ form.cliente|add_class:"form-control input-box rm-border"}} {% for error in form.cliente.errors %}
                  <p class="text-danger">{{ error }}</p>
                  {% endfor %}
                  <br />
                  <p class="mb-1">Servicio:</p>
                  {{ form.servicio|add_class:"form-control input-box rm-border"}} {% for error in form.servicio.errors %}
                  <p class="text-danger">{{ error }}</p>
                  {% endfor %}
                  <br />
                  <br />
                  <p class="mb-1">Fecha:</p>
                  {{ form.fecha|add_class:"form-control input-box rm-border" }}
                  {% for error in form.fecha.errors %}
                  <p class="text-danger">{{ error }}</p>
                  {% endfor %}
                  <br />
                  <p class="mb-1">Hora:</p>
                  {{ form.hora|add_class:"form-control input-box rm-border" }}
                  {% for error in form.hora.errors %}
                  <p class="text-danger"><strong>{{ error }}</strong></p>
                  {% endfor %}
                </div>
              </div>

              <div class="form-group row justify-content-center mb-0">
                <div class="col-md-12 px-3">
                  <input
                    type="submit"
                    value="Guardar"
                    class="btn btn-block btn-light rm-border"
                  />
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </body>
</html>

Scorpion/templates/citas.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Citas Agendadas</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <link rel="icon" type="image/png" href="{% static 'img/lobster.png' %}" />
  </head>
  <body class="bg-dark">
    <div class="container mt-5">
      <h1 class="text-center text-light mb-4">Citas Agendadas</h1>
      <table class="table table-bordered table-dark">
        <thead>
          <tr>
            <th>ID</th>
            <th>Cliente</th>
            <th>Servicio</th>
            <th>Fecha</th>
            <th>Hora</th>
          </tr>
        </thead>
        <tbody>
          {% for cita in citas %}
          <tr>
            <td>{{ cita.id }}</td>
            <td>{{ cita.cliente.nombre }} {{ cita.cliente.apellido }}</td>
            <td>
              <ul>
                {% for servicio in cita.servicio.all %}
                <li>{{ servicio.nombre }}</li>
                {% endfor %}
              </ul>
            </td>
            <td>{{ cita.fecha }}</td>
            <td>{{ cita.hora }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      <a href="{% url 'index' %}" class="btn btn-primary">Volver</a>
    </div>
  </body>

</html>

Scorpion/templates/cliente_form.html
{% load static %} {% load custom_filters %}

<!DOCTYPE html>
<html>
  <head>
    <title>Crear Cliente</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/test.css' %}" />
    <link rel="icon" type="image/png" href="{% static 'img/lobster.png' %}" />
  </head>
  <body class="btn-dark">
    <br />
    <div class="container">
      <div class="row justify justify-content-center">
        <div class="col-11 col-md-8 col-lg-6 col-xl-5">
          <form method="post">
            {% csrf_token %} {% if form.rut.errors %}
            <ul>
              {% for error in form.rut.errors %}
              <li>{{ error }}</li>
              {% endfor %}
            </ul>
            {% endif %}
            <div class="card custom-card">
              <div class="row mt-0">
                <div class="col-md-12">
                  <h4 class="">Creación de Cliente</h4>
                </div>
              </div>
              <div class="form-group row mb-3">
                <div class="col-md-12 mb-0">
                  <br />
                  <p class="mb-1">Rut</p>
                  {{ form.rut|add_class:"form-control input-box rm-border" }}
                  <br />
                  <p class="mb-1">Nombre</p>
                  {{ form.nombre|add_class:"form-control input-box rm-border" }}
                  <br />
                  <p class="mb-1">Apellido</p>
                  {{ form.apellido|add_class:"form-control input-box rm-border"}}
                  <br />
                  <p class="mb-1">Teléfono</p>
                  {{ form.telefono|add_class:"form-control input-box rm-border"}}
                  <br />
                  <p class="mb-1">Email</p>
                  {{ form.email|add_class:"form-control input-box rm-border" }}
                </div>
              </div>

              {% if cliente_existente %}
              <div class="form-group row mb-0">
                <div class="col-md-12">
                  <p>El cliente ya existe. ¿Desea continuar?</p>
                  <a
                    href="{% url 'crear_cita' %}"
                    class="btn btn-info bg-primary"
                    >Continuar</a
                  >
                </div>
              </div>
              {% endif %}
              <div class="form-group row">
                <div class="col-md-12 mb-2"></div>
              </div>
              <div class="form-group row justify-content-center mb-0">
                <div class="col-md-12 px-3">
                  <input
                    type="submit"
                    value="Guardar"
                    class="btn btn-block btn-light rm-border"
                  />
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>

    <script>
      /* FUNCION RUT FORMATO XX.XXX.XXX-X OR X.XXX.XXX-X */
      function formatRut(input) {
        var rut = input.value.replace(/\./g, "").replace(/-/g, "");
        if (rut.length > 1) {
          rut =
            rut.substring(0, rut.length - 1) + "-" + rut.charAt(rut.length - 1);
        }
        if (rut.length > 3 && rut.length <= 6) {
          rut =
            rut.substring(0, rut.length - 3) +
            "." +
            rut.substring(rut.length - 3);
        }
        if (rut.length > 6) {
          rut =
            rut.substring(0, rut.length - 8) +
            "." +
            rut.substring(rut.length - 8, rut.length - 5) +
            "." +
            rut.substring(rut.length - 5, rut.length - 2) +
            "-" +
            rut.charAt(rut.length - 1);
        }
        input.value = rut;
      }
    </script>
  </body>
</html>

Scorpion/templates/confirmacion.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Confirmación de Cita</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <link rel="icon" type="image/png" href="{% static 'img/lobster.png' %}" />
    <link rel="stylesheet" href="{% static 'css/map.css' %}">
    <script src="{% static 'js/app.js' %}"></script>
  </head>
  <body class="bg-dark">
    <div class="container mt-5">
      <br /><br /><br />
      <div class="card" style="background-color: #5c6bc0">
        <div class="card-body">
          <h5 class="card-title">Cita Agendada</h5>
          <p class="card-text">Has agendado una cita para:</p>
          <ul>
            <li><strong>Cliente:</strong> {{ cliente }}</li>
            <li><strong>Hora:</strong> {{ hora }}</li>
            <li><strong>Fecha:</strong> {{ fecha }}</li>
            <li>
              <strong>Servicios:</strong>
              <ul>
                {% for servicio in servicios %}
                <li>{{ servicio }}</li>
                {% endfor %}
              </ul>
            </li>
          </ul>
          <a href="{% url 'index' %}" class="btn btn-primary">Volver al Home</a>
          <div class="container">
            <section class="mx-auto my-5" style="max-width: 23rem;">
              <div class="card map-card">
                <div id="map-container-google-1" class="z-depth-1-half map-container">
                  <!--URL GOOGLE MAPS-->
                  <iframe src="https://maps.google.com/maps?q=manhatan&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" style="border:0" allowfullscreen></iframe>
                </div>
                <div class="card-body closed px-0">
                  <!-- Contenido adicional del mapa -->
                </div>
              </div>
            </section>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

Scorpion/templates/index.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!--TITULO-->
    <title>Scorpion - Home</title>
    <!--END TITULO-->

    <!--ICONO PESTAÑA PÁGINA-->
    <link rel="icon" type="image/png" href="{% static 'img/lobster.png' %}" />
    <!--END ICONO-->

    <!--VINCULO ARCHIVO CSS / RAIZ APLICACION SCORPION STATIC/CSS/STYLE.CSS-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <!--END VINCULO-->

    <!--VINCULO FUENTES GOOGLE-->
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:wght@500;600&display=swap"
      rel="stylesheet"
    />
    <!--END-->

    <!--CDN BOOTSTRAP-->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <!--END CDN-->

    <!--CDN FONTAWESOME-->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
    />
    <!--END CDN-->
  </head>

  <!--BEGIN BODY-->
  <!--USO DE SISTEMA GRID BOOTSTRAP-->
  <!--USO DE ICONOS FONTAWESOME-->
  <body class="btn-dark">
    <div class="container">
      <div class="row">
        <div
          class="col-12 col-md-4 order-md-3 d-flex justify-content-end align-items-center"
        >
          <i
            class="fab fa-facebook"
            style="font-size: 45px; padding-right: 20px; color: #c9bdf2"
          ></i>
          <i
            class="fab fa-whatsapp"
            style="font-size: 45px; padding-right: 10px; color: #c9bdf2"
          ></i>
        </div>
        <div class="col-12 col-md-4 order-md-2 text-center">
          <img
            src="{% static 'img/logo.png' %}"
            class="img-fluid"
            alt="Imagen Responsiva"
          />
        </div>
        <div
          class="col-12 col-md-4 order-md-1 d-flex justify-content-start align-items-center"
        >
          <i
            class="fas fa-user"
            style="font-size: 45px; padding-right: 10px; color: #c9bdf2"
          ></i>
        </div>
      </div>
    </div>

    <div class="image-container">
      <img src="{% static 'img/cartoon.png' %}" alt="..." />
    </div>

    <div class="container">
      <div class="row justify-content-center mt-0">
        <div class="col-12 text-center">
          <p class="text">Un Nuevo concepto de Peluquería</p>
        </div>
        <div class="col-12 text-center">
          <button class="btn-hover color-7 custom-btn">
            <a
              href="{% url 'citas' %}"
              style="text-decoration: none; color: aliceblue"
              >Citas Agendadas</a
            >
          </button>
          <button class="btn-hover color-7 custom-btn">
            <a
              href="{% url 'servicios' %}"
              style="text-decoration: none; color: aliceblue"
              >Tipos de Servicios</a
            >
          </button>
        </div>
        <div class="col-12 text-center">
          <p class="text1">
            © 2023 ®Rulitos inc. Todos los derechos reservados.
          </p>
        </div>
      </div>
    </div>

    <!--LIBRERIAS JQUERY Y JS BOOTSTRAP-->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.min.js"></script>

    <!--END BODY-->
  </body>
</html>

Scorpion/templates/servicios.html
{% load static %}

<!DOCTYPE html>
<html lang="es">

<head>
  <meta charset="UTF-8">

  <!--TITULO-->
  <title>Servicios - Scorpion</title>
  <!--END TITULO-->

  <meta name="viewport" content="width=device-width, initial-scale=1">

  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
  <link rel="stylesheet" href="{% static 'css/services.css' %}">
  <link rel="icon" type="image/png" href="{% static 'img/lobster.png' %}">

</head>

<body>

  <div class="row">
    <div class="col-12 col-md-4 order-md-2 text-center">
      <a href="{% url 'index' %}"><img src="{% static 'img/logo.png' %}" class="img-fluid" alt="Imagen Responsiva"></a>
    </div>
  </div>

  <!-- partial:index.partial.html -->
  <main class="page-content">
    <div class="card">
      <div class="content">
        <h2 class="title" style="color: aliceblue;">Lifting de pestañas</h2>

        <button class="btn"><a href="{% url 'crear_cliente' %}" style="text-decoration: none; color: aliceblue;">Agendar
            Cita</a></button>
      </div>
    </div>
    <div class="card">
      <div class="content">
        <h2 class="title" style="color: aliceblue;">Barbería</h2>

        <button class="btn"><a href="{% url 'crear_cliente' %}" style="text-decoration: none; color: aliceblue;">Agendar
            Cita</a></button>
      </div>
    </div>
    <div class="card">
      <div class="content">
        <h2 class="title" style="color: aliceblue;">Coloracion</h2>

        <button class="btn"><a href="{% url 'crear_cliente' %}" style="text-decoration: none; color: aliceblue;">Agendar
            Cita</a></button>
      </div>
    </div>
    <div class="card">
      <div class="content">
        <h2 class="title" style="color: aliceblue;">Corte de Pelo</h2>

        <button class="btn"><a href="{% url 'crear_cliente' %}" style="text-decoration: none; color: aliceblue;">Agendar
            Cita</a></button>
      </div>
    </div>
    <div class="card">
      <div class="content">
        <h2 class="title" style="color: aliceblue;">Depilacion</h2>

        <button class="btn"><a href="{% url 'crear_cliente' %}" style="text-decoration: none; color: aliceblue;">Agendar
            Cita</a></button>
      </div>
    </div>
    <div class="card">
      <div class="content">
        <h2 class="title" style="color: aliceblue;">Parafinoterapia</h2>

        <button class="btn"><a href="{% url 'crear_cliente' %}" style="text-decoration: none; color: aliceblue;">Agendar
            Cita</a></button>
      </div>
    </div>
  </main>
  <!-- partial -->

</body>

</html>

</body>

</html>